<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Análisis de estadística paramétrica y no paramétrica | Predicting Student Test Scores</title>
  <meta name="description" content="3 Análisis de estadística paramétrica y no paramétrica | Predicting Student Test Scores" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Análisis de estadística paramétrica y no paramétrica | Predicting Student Test Scores" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jimaraurzola-dotcom/Predicting-Student-Test-Scores-_-MT-project" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Análisis de estadística paramétrica y no paramétrica | Predicting Student Test Scores" />
  
  
  

<meta name="author" content="Jimara Urzola y Jose Castro" />


<meta name="date" content="2026-10-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análisis-exploratorio-de-datos-eda.html"/>
<link rel="next" href="tabla-de-contingencia.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="index.html"><a href="index.html#contexto-de-los-datos-de-student-test-scores"><i class="fa fa-check"></i><b>1.0.1</b> Contexto de los datos de student test scores</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio de datos (EDA)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html#an%C3%A1lisis-exploratorio-de-exam_score-target"><i class="fa fa-check"></i><b>2.1</b> Análisis exploratorio de <code>exam_score</code> (Target)</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html#an%C3%A1lisis-de-las-variables-independientes-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>2.2</b> Análisis de las variables independientes (características)</a></li>
<li class="chapter" data-level="2.3" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>2.3</b> Análisis exploratorio bivariado</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-de-estadística-paramétrica-y-no-paramétrica.html"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html"><i class="fa fa-check"></i><b>3</b> Análisis de estadística paramétrica y no paramétrica</a></li>
<li class="chapter" data-level="4" data-path="tabla-de-contingencia.html"><a href="tabla-de-contingencia.html"><i class="fa fa-check"></i><b>4</b> Tabla de contingencia</a></li>
<li class="chapter" data-level="5" data-path="correlación-lineal.html"><a href="correlación-lineal.html"><i class="fa fa-check"></i><b>5</b> Correlación lineal</a></li>
<li class="chapter" data-level="6" data-path="conclusiones.html"><a href="conclusiones.html"><i class="fa fa-check"></i><b>6</b> Conclusiones</a></li>
<li class="divider"></li>
<li><a href="https://github.com/jimaraurzola-dotcom/Predicting-Student-Test-Scores-_-MT-project/tree/proyecto" target="_blank">Repositorio en GitHub</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Predicting Student Test Scores</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-de-estadística-paramétrica-y-no-paramétrica" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Análisis de estadística paramétrica y no paramétrica<a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#an%C3%A1lisis-de-estad%C3%ADstica-param%C3%A9trica-y-no-param%C3%A9trica" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo comparamos <code>exam_score</code> entre los grupos de cada variable categórica. En cada caso verificamos primero la normalidad por grupo. Como cada grupo tiene más de 5.000 observaciones, no usamos Shapiro-Wilk sino Lilliefors.</p>
<p>Si la normalidad no se cumple, no aplican el t-test ni el ANOVA y usamos sus alternativas no paramétricas: la prueba U de Mann-Whitney para dos grupos y Kruskal-Wallis para tres o más. Antes de cada una verificamos la homogeneidad de varianzas con la prueba de Levene centrada en la mediana, que es la indicada cuando los datos no son normales.</p>
<ul>
<li>¿El hecho de contar con acceso a internet influye en el desempeño académico de los estudiantes?</li>
</ul>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb84-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb84-2" tabindex="-1"></a>  <span class="fu">group_by</span>(internet_access) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb84-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb84-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb84-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb84-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb84-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   internet_access      n est_lt      p_lt
##   &lt;chr&gt;            &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 no               50577 0.0279 5.04e-102
## 2 yes             579423 0.0236 0</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los dos grupos: con acceso a internet <span class="math inline">\((D = 0.0236, p-valor &lt; 0.001)\)</span> y sin acceso <span class="math inline">\((D = 0.0279, p-valor &lt; 0.001)\)</span>. Usamos entonces la prueba U de Mann-Whitney.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb86-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(internet_access), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value   Pr(&gt;F)    
## group      1  60.968 5.81e-15 ***
##       629998                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(1, 629998)} = 60.97, p-valor &lt; 0.001)\)</span>. Sin embargo, las desviaciones estándar de los dos grupos son 19,3 y 18,9 (tabla del EDA), una diferencia de 0,4 puntos. Con 630.000 observaciones la prueba detecta diferencias muy pequeñas, así que consideramos que las varianzas son similares. Lo mismo ocurre en todas las variables de este capítulo.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb88-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb88-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb88-2" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(exam_score <span class="sc">~</span> internet_access, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.        group1 group2    n1     n2    statistic      p
## * &lt;chr&gt;      &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt;  &lt;int&gt;        &lt;dbl&gt;  &lt;dbl&gt;
## 1 exam_score no     yes    50577 579423 14565777034. 0.0266</code></pre>
<p>La prueba U de Mann-Whitney muestra, con una confianza del 95%, una diferencia estadísticamente significativa en <code>exam_score</code> entre los estudiantes con y sin acceso a internet <span class="math inline">\((W = 14565777034, p-valor = 0.0266)\)</span>.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb90-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb90-2" tabindex="-1"></a>  <span class="fu">wilcox_effsize</span>(exam_score <span class="sc">~</span> internet_access, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.        group1 group2 effsize    n1     n2 magnitude
## * &lt;chr&gt;      &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt;  &lt;int&gt; &lt;ord&gt;    
## 1 exam_score no     yes    0.00279 50577 579423 small</code></pre>
<p>El tamaño del efecto es <span class="math inline">\(r = 0.0028\)</span>, prácticamente nulo. Aunque la diferencia es significativa, el acceso a internet no tiene relevancia práctica en el desempeño: las medianas difieren en menos de un punto.</p>
<ul>
<li>¿Existen diferencias en el desempeño académico según el género del estudiante?</li>
</ul>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb92-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb92-2" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb92-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb92-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb92-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb92-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb92-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   gender      n est_lt      p_lt
##   &lt;chr&gt;   &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 female 208310 0.0238 2.66e-303
## 2 male   210593 0.0219 3.31e-260
## 3 other  211097 0.0259 0</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los tres grupos: female <span class="math inline">\((D = 0.0238, p-valor &lt; 0.001)\)</span>, male <span class="math inline">\((D = 0.0219, p-valor &lt; 0.001)\)</span> y other <span class="math inline">\((D = 0.0259, p-valor &lt; 0.001)\)</span>. Usamos entonces Kruskal-Wallis.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb94-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(gender), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value    Pr(&gt;F)    
## group      2   64.94 &lt; 2.2e-16 ***
##       629997                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(2, 629997)} = 64.94, p-valor &lt; 0.001)\)</span>, pero las desviaciones estándar por grupo van de 18,8 a 19,1 (tabla del EDA), una diferencia mínima.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb96-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(exam_score <span class="sc">~</span> gender, <span class="at">data =</span> trainset)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  exam_score by gender
## Kruskal-Wallis chi-squared = 81.54, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>La prueba de Kruskal-Wallis indica, con una confianza del 95%, que hay una diferencia estadísticamente significativa en <code>exam_score</code> entre al menos dos de los grupos de género <span class="math inline">\((\chi^2_{(2)} = 81.54, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb98-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> trainset<span class="sc">$</span>exam_score,</span>
<span id="cb98-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb98-2" tabindex="-1"></a>                     <span class="at">g =</span> trainset<span class="sc">$</span>gender,</span>
<span id="cb98-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb98-3" tabindex="-1"></a>                     <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb98-4" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  trainset$exam_score and trainset$gender 
## 
##       female  male   
## male  5.1e-06 -      
## other 1e-04   &lt; 2e-16
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con el ajuste de Bonferroni los tres pares de grupos difieren entre sí <span class="math inline">\((p &lt; 0.001)\)</span>. Sin embargo, las medianas van de 62,5 a 62,6 y las medias de 62,2 a 62,8: la diferencia es significativa por el tamaño de muestra, pero no tiene relevancia práctica.</p>
<ul>
<li>¿La calidad del sueño percibida por el estudiante se relaciona con su desempeño en el examen?</li>
</ul>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb100-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb100-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb100-2" tabindex="-1"></a>  <span class="fu">group_by</span>(sleep_quality) <span class="sc">%&gt;%</span></span>
<span id="cb100-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb100-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb100-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb100-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb100-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb100-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   sleep_quality      n est_lt      p_lt
##   &lt;chr&gt;          &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 average       203236 0.0243 4.51e-309
## 2 good          213089 0.0381 0        
## 3 poor          213675 0.0212 3.19e-246</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los tres grupos: average <span class="math inline">\((D = 0.0243, p-valor &lt; 0.001)\)</span>, good <span class="math inline">\((D = 0.0381, p-valor &lt; 0.001)\)</span> y poor <span class="math inline">\((D = 0.0212, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb102-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(sleep_quality), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value    Pr(&gt;F)    
## group      2    85.1 &lt; 2.2e-16 ***
##       629997                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(2, 629997)} = 85.1, p-valor &lt; 0.001)\)</span>, aunque las desviaciones estándar por grupo van de 18,1 a 18,6 (tabla del EDA).</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb104-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(exam_score <span class="sc">~</span> sleep_quality, <span class="at">data =</span> trainset)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  exam_score by sleep_quality
## Kruskal-Wallis chi-squared = 33168, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>La prueba de Kruskal-Wallis indica, con una confianza del 95%, que hay una diferencia estadísticamente significativa en <code>exam_score</code> entre al menos dos de los grupos de calidad del sueño <span class="math inline">\((\chi^2_{(2)} = 33168, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb106-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> trainset<span class="sc">$</span>exam_score,</span>
<span id="cb106-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb106-2" tabindex="-1"></a>                     <span class="at">g =</span> trainset<span class="sc">$</span>sleep_quality,</span>
<span id="cb106-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb106-3" tabindex="-1"></a>                     <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb106-4" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  trainset$exam_score and trainset$sleep_quality 
## 
##      average good  
## good &lt;2e-16  -     
## poor &lt;2e-16  &lt;2e-16
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con el ajuste de Bonferroni los tres pares difieren entre sí <span class="math inline">\((p &lt; 0.001)\)</span>. Aquí la diferencia sí es relevante: la mediana pasa de 57,2 en poor a 62,6 en average y 68,2 en good.</p>
<ul>
<li>¿La calificación que los estudiantes dan a las instalaciones educativas está relacionada con su desempeño académico?</li>
</ul>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb108-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb108-2" tabindex="-1"></a>  <span class="fu">group_by</span>(facility_rating) <span class="sc">%&gt;%</span></span>
<span id="cb108-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb108-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb108-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb108-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb108-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb108-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   facility_rating      n est_lt      p_lt
##   &lt;chr&gt;            &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 high            203540 0.0362 0        
## 2 low             212378 0.0207 1.67e-232
## 3 medium          214082 0.0236 1.49e-308</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los tres grupos: high <span class="math inline">\((D = 0.0362, p-valor &lt; 0.001)\)</span>, low <span class="math inline">\((D = 0.0207, p-valor &lt; 0.001)\)</span> y medium <span class="math inline">\((D = 0.0236, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb110-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(facility_rating), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value  Pr(&gt;F)  
## group      2  3.9771 0.01874 *
##       629997                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(2, 629997)} = 3.98, p-valor = 0.0187)\)</span>, aunque las desviaciones estándar por grupo son casi idénticas, de 18,5 a 18,6 (tabla del EDA).</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb112-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(exam_score <span class="sc">~</span> facility_rating, <span class="at">data =</span> trainset)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  exam_score by facility_rating
## Kruskal-Wallis chi-squared = 20684, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>La prueba de Kruskal-Wallis indica, con una confianza del 95%, que hay una diferencia estadísticamente significativa en <code>exam_score</code> entre al menos dos de los grupos de calificación de instalaciones <span class="math inline">\((\chi^2_{(2)} = 20684, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb114-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> trainset<span class="sc">$</span>exam_score,</span>
<span id="cb114-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb114-2" tabindex="-1"></a>                     <span class="at">g =</span> trainset<span class="sc">$</span>facility_rating,</span>
<span id="cb114-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb114-3" tabindex="-1"></a>                     <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb114-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb114-4" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  trainset$exam_score and trainset$facility_rating 
## 
##        high   low   
## low    &lt;2e-16 -     
## medium &lt;2e-16 &lt;2e-16
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con el ajuste de Bonferroni los tres pares difieren entre sí <span class="math inline">\((p &lt; 0.001)\)</span>. La mediana pasa de 58,3 en low a 63,1 en medium y 67,3 en high.</p>
<ul>
<li>¿La dificultad percibida del examen afecta la calificación obtenida por los estudiantes?</li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb116-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb116-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb116-2" tabindex="-1"></a>  <span class="fu">group_by</span>(exam_difficulty) <span class="sc">%&gt;%</span></span>
<span id="cb116-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb116-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb116-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb116-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb116-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb116-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   exam_difficulty      n est_lt      p_lt
##   &lt;chr&gt;            &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 easy            176540 0.0217 8.05e-214
## 2 hard             99478 0.0255 7.47e-168
## 3 moderate        353982 0.0243 0</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los tres grupos: easy <span class="math inline">\((D = 0.0217, p-valor &lt; 0.001)\)</span>, hard <span class="math inline">\((D = 0.0255, p-valor &lt; 0.001)\)</span> y moderate <span class="math inline">\((D = 0.0243, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb118-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(exam_difficulty), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value    Pr(&gt;F)    
## group      2  50.325 &lt; 2.2e-16 ***
##       629997                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(2, 629997)} = 50.33, p-valor &lt; 0.001)\)</span>, aunque las desviaciones estándar por grupo van de 18,7 a 19,1 (tabla del EDA).</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb120-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(exam_score <span class="sc">~</span> exam_difficulty, <span class="at">data =</span> trainset)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  exam_score by exam_difficulty
## Kruskal-Wallis chi-squared = 53.954, df = 2, p-value = 1.924e-12</code></pre>
<p>La prueba de Kruskal-Wallis indica, con una confianza del 95%, que hay una diferencia estadísticamente significativa en <code>exam_score</code> entre al menos dos de los grupos de dificultad del examen <span class="math inline">\((\chi^2_{(2)} = 53.95, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb122-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> trainset<span class="sc">$</span>exam_score,</span>
<span id="cb122-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb122-2" tabindex="-1"></a>                     <span class="at">g =</span> trainset<span class="sc">$</span>exam_difficulty,</span>
<span id="cb122-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb122-3" tabindex="-1"></a>                     <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb122-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb122-4" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  trainset$exam_score and trainset$exam_difficulty 
## 
##          easy    hard
## hard     3.0e-09 -   
## moderate 1.9e-10 0.41
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con el ajuste de Bonferroni, easy difiere de hard y de moderate <span class="math inline">\((p &lt; 0.001)\)</span>, pero hard y moderate no difieren <span class="math inline">\((p = 0.41)\)</span>. Las medianas van de 62,5 a 62,8, así que la dificultad percibida no tiene relevancia práctica en la nota.</p>
<ul>
<li>¿El método de estudio empleado influye en el puntaje obtenido en el examen?</li>
</ul>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb124-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb124-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb124-2" tabindex="-1"></a>  <span class="fu">group_by</span>(study_method) <span class="sc">%&gt;%</span></span>
<span id="cb124-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb124-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb124-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb124-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb124-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb124-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 4
##   study_method       n est_lt      p_lt
##   &lt;chr&gt;          &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 coaching      131697 0.0478 0        
## 2 group study   123009 0.0199 1.75e-124
## 3 mixed         123086 0.0317 9.88e-324
## 4 online videos 121077 0.0238 1.05e-176
## 5 self-study    131131 0.0258 4.69e-225</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los cinco grupos: coaching <span class="math inline">\((D = 0.0478)\)</span>, group study <span class="math inline">\((D = 0.0199)\)</span>, mixed <span class="math inline">\((D = 0.0317)\)</span>, online videos <span class="math inline">\((D = 0.0238)\)</span> y self-study <span class="math inline">\((D = 0.0258)\)</span>, todos con <span class="math inline">\(p-valor &lt; 0.001\)</span>.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb126-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(study_method), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value    Pr(&gt;F)    
## group      4  63.867 &lt; 2.2e-16 ***
##       629995                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(4, 629995)} = 63.87, p-valor &lt; 0.001)\)</span>, aunque las desviaciones estándar por grupo van de 18,2 a 18,7 (tabla del EDA).</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb128-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(exam_score <span class="sc">~</span> study_method, <span class="at">data =</span> trainset)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  exam_score by study_method
## Kruskal-Wallis chi-squared = 29548, df = 4, p-value &lt; 2.2e-16</code></pre>
<p>La prueba de Kruskal-Wallis indica, con una confianza del 95%, que hay una diferencia estadísticamente significativa en <code>exam_score</code> entre al menos dos de los métodos de estudio <span class="math inline">\((\chi^2_{(4)} = 29548, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb130-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> trainset<span class="sc">$</span>exam_score,</span>
<span id="cb130-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb130-2" tabindex="-1"></a>                     <span class="at">g =</span> trainset<span class="sc">$</span>study_method,</span>
<span id="cb130-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb130-3" tabindex="-1"></a>                     <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb130-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb130-4" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  trainset$exam_score and trainset$study_method 
## 
##               coaching group study mixed  online videos
## group study   &lt;2e-16   -           -      -            
## mixed         &lt;2e-16   &lt;2e-16      -      -            
## online videos &lt;2e-16   &lt;2e-16      &lt;2e-16 -            
## self-study    &lt;2e-16   &lt;2e-16      &lt;2e-16 &lt;2e-16       
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con el ajuste de Bonferroni los diez pares de métodos difieren entre sí <span class="math inline">\((p &lt; 0.001)\)</span>. Es la variable con mayor diferencia: la mediana va de 57,3 en self-study a 69,3 en coaching.</p>
<ul>
<li>¿El programa académico que cursa el estudiante se relaciona con su desempeño en el examen?</li>
</ul>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb132-1" tabindex="-1"></a>trainset <span class="sc">%&gt;%</span></span>
<span id="cb132-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb132-2" tabindex="-1"></a>  <span class="fu">group_by</span>(course) <span class="sc">%&gt;%</span></span>
<span id="cb132-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb132-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(exam_score),</span>
<span id="cb132-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb132-4" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>statistic,</span>
<span id="cb132-5"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb132-5" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(exam_score)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 4
##   course       n est_lt      p_lt
##   &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1 b.com   110932 0.0226 5.06e-146
## 2 b.sc    111554 0.0254 1.91e-185
## 3 b.tech  131236 0.0254 1.20e-218
## 4 ba       61989 0.0278 3.70e-124
## 5 bba      75644 0.0275 4.20e-148
## 6 bca      88721 0.0240 1.25e-131
## 7 diploma  49924 0.0245 1.11e- 76</code></pre>
<p>La prueba de Lilliefors muestra que <code>exam_score</code> no tiene comportamiento normal en ninguno de los siete programas académicos (en todos los casos <span class="math inline">\(p-valor &lt; 0.001\)</span>).</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb134-1" tabindex="-1"></a><span class="fu">leveneTest</span>(exam_score <span class="sc">~</span> <span class="fu">factor</span>(course), <span class="at">data =</span> trainset, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##           Df F value    Pr(&gt;F)    
## group      6  49.585 &lt; 2.2e-16 ***
##       629993                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene rechaza la igualdad de varianzas <span class="math inline">\((F_{(6, 629993)} = 49.59, p-valor &lt; 0.001)\)</span>, aunque las desviaciones estándar por grupo van de 18,4 a 19,3 (tabla del EDA).</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb136-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(exam_score <span class="sc">~</span> course, <span class="at">data =</span> trainset)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  exam_score by course
## Kruskal-Wallis chi-squared = 199.28, df = 6, p-value &lt; 2.2e-16</code></pre>
<p>La prueba de Kruskal-Wallis indica, con una confianza del 95%, que hay una diferencia estadísticamente significativa en <code>exam_score</code> entre al menos dos de los programas académicos <span class="math inline">\((\chi^2_{(6)} = 199.28, p-valor &lt; 0.001)\)</span>.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb138-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> trainset<span class="sc">$</span>exam_score,</span>
<span id="cb138-2"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb138-2" tabindex="-1"></a>                     <span class="at">g =</span> trainset<span class="sc">$</span>course,</span>
<span id="cb138-3"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb138-3" tabindex="-1"></a>                     <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb138-4"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html#cb138-4" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  trainset$exam_score and trainset$course 
## 
##         b.com   b.sc    b.tech  ba      bba     bca  
## b.sc    1.000   -       -       -       -       -    
## b.tech  1.000   1.000   -       -       -       -    
## ba      3.1e-07 9.3e-07 3.1e-09 -       -       -    
## bba     &lt; 2e-16 &lt; 2e-16 &lt; 2e-16 &lt; 2e-16 -       -    
## bca     1.000   1.000   1.000   4.2e-10 7.1e-13 -    
## diploma 1.000   1.000   1.000   0.016   &lt; 2e-16 0.199
## 
## P value adjustment method: bonferroni</code></pre>
<p>Con el ajuste de Bonferroni, b.com, b.sc, b.tech, bca y diploma no difieren entre sí <span class="math inline">\((p &gt; 0.05)\)</span>; las diferencias aparecen con bba y ba. Aun así, las medianas solo van de 61,8 a 63,6, así que el programa académico no tiene relevancia práctica en la nota.</p>
<p>En las siete variables las pruebas resultaron significativas, algo esperable con 630.000 observaciones. Por eso juzgamos la relevancia de cada variable por la diferencia entre grupos: <code>study_method</code>, <code>sleep_quality</code> y <code>facility_rating</code> muestran diferencias de 9 a 12 puntos en la mediana, mientras que en <code>gender</code>, <code>internet_access</code>, <code>exam_difficulty</code> y <code>course</code> las medianas difieren en menos de 2 puntos.</p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análisis-exploratorio-de-datos-eda.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tabla-de-contingencia.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
