<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Correlación | Predicting Student Test Scores</title>
  <meta name="description" content="5 Correlación | Predicting Student Test Scores" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Correlación | Predicting Student Test Scores" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jimaraurzola-dotcom/Predicting-Student-Test-Scores-_-MT-project" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Correlación | Predicting Student Test Scores" />
  
  
  

<meta name="author" content="Jimara Urzola" />


<meta name="date" content="2026-09-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tabla-de-contingencia.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="index.html"><a href="index.html#contexto-de-los-datos-de-student-test-scores"><i class="fa fa-check"></i><b>1.0.1</b> Contexto de los datos de student test scores</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio de datos (EDA)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html#an%C3%A1lisis-exploratorio-de-exam_score-target"><i class="fa fa-check"></i><b>2.1</b> Análisis exploratorio de <code>exam_score</code> (Target)</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html#an%C3%A1lisis-de-las-variables-independientes-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>2.2</b> Análisis de las variables independientes (características)</a></li>
<li class="chapter" data-level="2.3" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>2.3</b> Análisis exploratorio bivariado</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-de-estadística-paramétrica-y-no-paramétrica.html"><a href="análisis-de-estadística-paramétrica-y-no-paramétrica.html"><i class="fa fa-check"></i><b>3</b> Análisis de estadística paramétrica y no paramétrica</a></li>
<li class="chapter" data-level="4" data-path="tabla-de-contingencia.html"><a href="tabla-de-contingencia.html"><i class="fa fa-check"></i><b>4</b> Tabla de contingencia</a></li>
<li class="chapter" data-level="5" data-path="correlación.html"><a href="correlación.html"><i class="fa fa-check"></i><b>5</b> Correlación</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Predicting Student Test Scores</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correlación" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Correlación<a href="correlación.html#correlaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En el EDA ya habíamos observado, a través de diagramas de dispersión, que <code>study_hours</code> y <code>class_attendance</code> parecían tener una relación positiva con <code>exam_score</code>, mientras que <code>age</code> y <code>sleep_hours</code> no mostraban un patrón claro. En esta sección cuantificamos esas relaciones con el coeficiente de correlación.</p>
<p>Como ya establecimos que <code>exam_score</code> no sigue una distribución normal (Lilliefors, sección anterior), primero verificamos la normalidad de las cuatro variables numéricas independientes para decidir entre correlación de Pearson (paramétrica) o de Spearman (no paramétrica). Al igual que antes, descartamos Shapiro-Wilk por el tamaño de la muestra (630.000) y usamos Lilliefors.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="correlación.html#cb114-1" tabindex="-1"></a><span class="fu">c</span>(<span class="at">age =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>age)<span class="sc">$</span>statistic,</span>
<span id="cb114-2"><a href="correlación.html#cb114-2" tabindex="-1"></a>  <span class="at">study_hours =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>study_hours)<span class="sc">$</span>statistic,</span>
<span id="cb114-3"><a href="correlación.html#cb114-3" tabindex="-1"></a>  <span class="at">class_attendance =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>class_attendance)<span class="sc">$</span>statistic,</span>
<span id="cb114-4"><a href="correlación.html#cb114-4" tabindex="-1"></a>  <span class="at">sleep_hours =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>sleep_hours)<span class="sc">$</span>statistic)</span></code></pre></div>
<pre><code>##              age.D      study_hours.D class_attendance.D      sleep_hours.D 
##         0.11515884         0.06276541         0.06111424         0.07380016</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="correlación.html#cb116-1" tabindex="-1"></a><span class="fu">c</span>(<span class="at">age =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>age)<span class="sc">$</span>p.value,</span>
<span id="cb116-2"><a href="correlación.html#cb116-2" tabindex="-1"></a>  <span class="at">study_hours =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>study_hours)<span class="sc">$</span>p.value,</span>
<span id="cb116-3"><a href="correlación.html#cb116-3" tabindex="-1"></a>  <span class="at">class_attendance =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>class_attendance)<span class="sc">$</span>p.value,</span>
<span id="cb116-4"><a href="correlación.html#cb116-4" tabindex="-1"></a>  <span class="at">sleep_hours =</span> <span class="fu">lillie.test</span>(trainset<span class="sc">$</span>sleep_hours)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>##              age      study_hours class_attendance      sleep_hours 
##                0                0                0                0</code></pre>
<p>Ninguna de las cuatro variables numéricas sigue una distribución normal (<code>age</code>: D = 0,1152; <code>study_hours</code>: D = 0,0628; <code>class_attendance</code>: D = 0,0611; <code>sleep_hours</code>: D = 0,0738; en los cuatro casos p-valor &lt; 0,001). Por lo tanto, usamos el coeficiente de correlación de Spearman en lugar de Pearson, consistente con el enfoque no paramétrico usado en toda la sección anterior.</p>
<ul>
<li>Matriz de correlación de Spearman entre las variables numéricas:</li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="correlación.html#cb118-1" tabindex="-1"></a>numericas <span class="ot">&lt;-</span> trainset <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="correlación.html#cb118-2" tabindex="-1"></a>  <span class="fu">select</span>(age, study_hours, class_attendance, sleep_hours, exam_score)</span>
<span id="cb118-3"><a href="correlación.html#cb118-3" tabindex="-1"></a></span>
<span id="cb118-4"><a href="correlación.html#cb118-4" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(numericas, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##                    age study_hours class_attendance sleep_hours exam_score
## age              1.000       0.008            0.006       0.006      0.007
## study_hours      0.008       1.000            0.087       0.043      0.770
## class_attendance 0.006       0.087            1.000       0.029      0.352
## sleep_hours      0.006       0.043            0.029       1.000      0.160
## exam_score       0.007       0.770            0.352       0.160      1.000</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="correlación.html#cb120-1" tabindex="-1"></a><span class="fu">ggcorr</span>(numericas, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">&quot;pairwise&quot;</span>, <span class="st">&quot;spearman&quot;</span>),</span>
<span id="cb120-2"><a href="correlación.html#cb120-2" tabindex="-1"></a>       <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">label_round =</span> <span class="dv">2</span>,</span>
<span id="cb120-3"><a href="correlación.html#cb120-3" tabindex="-1"></a>       <span class="at">low =</span> <span class="st">&quot;#f8f4ff&quot;</span>, <span class="at">mid =</span> <span class="st">&quot;#c5b0ff&quot;</span>, <span class="at">high =</span> <span class="st">&quot;#2f0be0&quot;</span>,</span>
<span id="cb120-4"><a href="correlación.html#cb120-4" tabindex="-1"></a>       <span class="at">hjust =</span> <span class="fl">0.8</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb120-5"><a href="correlación.html#cb120-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Matriz de correlación de Spearman&quot;</span>)</span></code></pre></div>
<p><img src="Predicting-Student-Test-Scores-Book_files/figure-html/correlacion%20heatmap-1.png" alt="" width="672" /></p>
<p>La matriz confirma lo observado visualmente en el EDA: <code>study_hours</code> es, por lejos, la variable más correlacionada con <code>exam_score</code>; le sigue <code>class_attendance</code> con una correlación moderada-débil; <code>sleep_hours</code> y <code>age</code> muestran correlaciones muy débiles, tanto con <code>exam_score</code> como entre ellas.</p>
<ul>
<li><code>study_hours</code> vs <code>exam_score</code></li>
</ul>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="correlación.html#cb121-1" tabindex="-1"></a><span class="fu">cor.test</span>(trainset<span class="sc">$</span>study_hours, trainset<span class="sc">$</span>exam_score, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  trainset$study_hours and trainset$exam_score
## S = 9.5952e+15, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.7697575</code></pre>
<p>Se obtiene un coeficiente <span class="math inline">\(\rho = 0.7698\)</span> <span class="math inline">\((S = 9.5952e+15, p-valor &lt; 0.001)\)</span>. Con una confianza del 95%, existe evidencia de una correlación positiva muy fuerte y estadísticamente significativa entre las horas de estudio y la calificación del examen: a más horas de estudio, mayor es la nota. Este es, por lejos, el predictor numérico más fuerte del dataset.</p>
<ul>
<li><code>class_attendance</code> vs <code>exam_score</code></li>
</ul>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="correlación.html#cb123-1" tabindex="-1"></a><span class="fu">cor.test</span>(trainset<span class="sc">$</span>class_attendance, trainset<span class="sc">$</span>exam_score, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  trainset$class_attendance and trainset$exam_score
## S = 2.7025e+16, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##      rho 
## 0.351515</code></pre>
<p>Se obtiene un coeficiente <span class="math inline">\(\rho = 0.3515\)</span> <span class="math inline">\((S = 2.7025e+16, p-valor &lt; 0.001)\)</span>, lo que corresponde a una correlación positiva débil-moderada: la asistencia a clases está relacionada con el desempeño académico, pero de forma bastante más modesta que las horas de estudio.</p>
<ul>
<li><code>sleep_hours</code> vs <code>exam_score</code></li>
</ul>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="correlación.html#cb125-1" tabindex="-1"></a><span class="fu">cor.test</span>(trainset<span class="sc">$</span>sleep_hours, trainset<span class="sc">$</span>exam_score, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  trainset$sleep_hours and trainset$exam_score
## S = 3.5005e+16, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.1600479</code></pre>
<p>Se obtiene un coeficiente <span class="math inline">\(\rho = 0.1600\)</span> <span class="math inline">\((S = 3.5005e+16, p-valor &lt; 0.001)\)</span>. Aunque estadísticamente significativa, la correlación es muy débil, casi nula en la práctica: dormir más o menos horas prácticamente no se traduce en diferencias en el puntaje del examen.</p>
<ul>
<li><code>age</code> vs <code>exam_score</code></li>
</ul>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="correlación.html#cb127-1" tabindex="-1"></a><span class="fu">cor.test</span>(trainset<span class="sc">$</span>age, trainset<span class="sc">$</span>exam_score, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  trainset$age and trainset$exam_score
## S = 4.1376e+16, p-value = 1.303e-08
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##         rho 
## 0.007163204</code></pre>
<p>Se obtiene un coeficiente <span class="math inline">\(\rho = 0.0072\)</span> <span class="math inline">\((S = 4.1376e+16, p-valor = 1.303e-08)\)</span>. A pesar de que el tamaño de muestra hace que hasta esta correlación tan pequeña resulte “significativa”, el coeficiente es prácticamente cero: la edad del estudiante no tiene ninguna relación relevante con su desempeño en el examen, confirmando lo que ya se veía en el diagrama de dispersión del EDA.</p>
<p>En conjunto, de las cuatro variables numéricas independientes, <code>study_hours</code> es por mucho la que mejor se relaciona con <code>exam_score</code> (ρ = 0,77, correlación muy fuerte), seguida bastante más atrás por <code>class_attendance</code> (ρ = 0,35, débil-moderada). <code>sleep_hours</code> (ρ = 0,16) y <code>age</code> (ρ ≈ 0) prácticamente no aportan nada. Y comparando con las secciones anteriores, ninguna variable categórica (ni siquiera <code>sleep_quality</code> o <code>study_method</code>) se acerca a la fuerza de esta relación. Todo apunta a que <code>study_hours</code> va a ser el predictor más importante cuando lleguemos a la regresión lineal.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="tabla-de-contingencia.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
